// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqtnzlehtnpcrefribxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxdG56bGVodG5wY3JlZnJpYnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjEzNjQsImV4cCI6MjA3NDUzNzM2NH0.5mzCB0ixhq_mMOTyS83rUAZM_jhLHkcxSpeuifAw6wc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});